---
title: "South Fork Crooked River 2021 Genotyping"
output:
  html_document:
    df_print: paged
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: false
---

```{r, message=FALSE, warning=FALSE}
require(tidyverse)
require(DiagrammeR)
require(poppr)
require(genepop)
require(graph4lg)
require(related)
require(adegenet)
require(knitr)
require(magrittr)
```

# Readme

This is document is an R notebook. If you'd like view to pre-rendered figures, read a summary of analysis and interact with code, please open the relevant html file in a browser. 

To conduct a similar analyses on your computer, edit or run code: clone this repository into a directory on your local machine and open the .Rproj file in Rstudio.

# Rationale

This is the genotyping log for the 2021 South Fork Crooked River O. mykiss project

# Data Summary
## Sequence Data

- SFGL Run Number 019
- Gtseq Data using the SFGL Omy392 panel:  
- Raw data from UofO sequencing center is located at "/dfs/Omalley_Lab/fitz/Runs/4773"  
- Arrived demultiplexed, lane also contains albacore data from the Tal317 test  

- Controls and Omy data copied to dayan directory for project: "/dfs/Omalley_Lab/dayan/small_omy_projects/crooked_river_2021/raw_reads"  



